# Generated by Django 2.2 on 2019-04-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почта администрации',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_description', models.TextField(blank=True, help_text='Это описание выводится в подвале сайта под логотипом', null=True, verbose_name='Описание в подвале')),
                ('header_phone', models.CharField(blank=True, help_text='Этот телефон выводится в верхней части сайта', max_length=255, null=True, verbose_name='Телефон')),
                ('header_email', models.ForeignKey(blank=True, help_text='Эта почта будет выводиться в верхней части сайта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AdminEmails', verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.TextField(blank=True, help_text='При нажатии на кнопку "Узнать больше" пользователь будет перенаправлен на эту ссылку. Если ссылку оставить пустым кнопка "Узнать больше" не будет отображаться', max_length=1000, null=True, verbose_name='Сылка')),
                ('thumbnail', models.FileField(upload_to='index-page-slider/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер на главной странице',
            },
        ),
        migrations.CreateModel(
            name='SocialProfileLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.CharField(help_text='Указываем класс для иконок. Например, "fa fa-facebook". Список иконок можно посмотреть <a href="https://fontawesome.com/v4.7.0/icons/" target="_blank">тут</a>', max_length=255, verbose_name='Иконка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SiteSettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Ссылка на соц. сеть',
                'verbose_name_plural': 'Ссылки на соц. сети',
            },
        ),
        migrations.CreateModel(
            name='FooterMenuLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Отображаемый текст')),
                ('on_blank', models.BooleanField(default=False, verbose_name='Открывать в новой странице?')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SiteSettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
