# Generated by Django 2.2 on 2019-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermenulinks',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки в подвале сайта'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, help_text='При нажатии на кнопку "Узнать больше" пользователь будет перенаправлен на эту ссылку. Если ссылку оставить пустым кнопка "Узнать больше" не будет отображаться', max_length=1000, null=True, verbose_name='Сылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='thumbnail',
            field=models.FileField(help_text='Предпочтительный размер 1520x450', upload_to='index-page-slider/', verbose_name='Изображение'),
        ),
    ]
