# Generated by Django 2.2 on 2019-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190429_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandSmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('thumbnail', models.FileField(help_text='Предпочтительные размеры: 540x380', upload_to='grand-smeta/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(help_text='URL Endpoint name', max_length=255, unique=True, verbose_name='SLUG')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Гранд Смету',
                'verbose_name_plural': 'Гранд Смета',
            },
        ),
    ]
