# Generated by Django 2.2 on 2019-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grandsmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandsmeta',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
