# Generated by Django 2.2 on 2019-05-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grandsmeta_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='grand_smeta_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в Гранд Смета'),
        ),
    ]
