# Generated by Django 2.2 on 2019-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_grand_smeta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandsmeta',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='grandsmeta',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
