# Generated by Django 2.2 on 2019-05-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190527_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandsmeta',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
    ]
