# Generated by Django 2.2 on 2019-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190529_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='one_c_header_image',
            field=models.FileField(blank=True, null=True, upload_to='1c/headers/', verbose_name='Изображение на странице "1C"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_header_image',
            field=models.FileField(blank=True, null=True, upload_to='schedule/headers/', verbose_name='Изображение на странице "Учебный центр"'),
        ),
    ]
