# Generated by Django 2.2 on 2019-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190529_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.TextField(blank=True, default='[]', verbose_name='Телефоны')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('work_schedule', models.TextField(blank=True, null=True, verbose_name='Режим работы')),
                ('emails', models.ManyToManyField(blank=True, to='core.AdminEmails', verbose_name="E-Mail'ы")),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
