# Generated by Django 2.2 on 2019-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='contacts/header/', verbose_name='Изображение на странице контактов'),
        ),
    ]
