# Generated by Django 2.2 on 2019-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190614_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='grand_service',
            field=models.TextField(blank=True, null=True, verbose_name='Текст Гранд Сервиса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grand_service_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение гранд сервиса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grand_smeta',
            field=models.TextField(blank=True, null=True, verbose_name='Текст Гранд Смета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grand_smeta_thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение Гранд смета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='Текст учебного центра'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение учебного центра'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_choose_us',
            field=models.TextField(blank=True, null=True, verbose_name='Почему выбирают нас?'),
        ),
    ]
