# Generated by Django 2.2 on 2019-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190614_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='grand_smeta_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение Гранд смета'),
        ),
    ]
