# Generated by Django 2.2 on 2019-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190614_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='grand_service_list_items',
            field=models.TextField(blank=True, default='[]', verbose_name='Маркированный список гранд сервиса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='grand_smeta_list_items',
            field=models.TextField(blank=True, default='[]', verbose_name='Маркированный список Гранд Смета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_list_items',
            field=models.TextField(blank=True, default='[]', verbose_name='Маркированный список учебного центра'),
        ),
    ]
