# Generated by Django 2.2 on 2019-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190926_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, help_text='HTML теги разрешены', null=True, verbose_name='Описание'),
        ),
    ]
