# Generated by Django 2.2 on 2019-10-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191017_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('order_index',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайдер на главной странице'},
        ),
        migrations.AddField(
            model_name='slider',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
