# Generated by Django 2.2 on 2019-10-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191017_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon_1c',
            field=models.TextField(blank=True, null=True, verbose_name='Текст дял иконки 1С'),
        ),
    ]
