# Generated by Django 2.2 on 2019-10-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesettings_icon_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon_certificates',
            field=models.TextField(blank=True, null=True, verbose_name='текст для иконки Сертификаты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_electronic_sign',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для иконки Электронные подписи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_grand_smeta',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для иконки Гранд Смета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_online_cashbox',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для иконки Онлайн Касс'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_schedule',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для иконки Учебного центра'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_1c',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для иконки 1С'),
        ),
    ]
