# Generated by Django 2.2 on 2019-10-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191021_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
