# Generated by Django 2.2 on 2019-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191021_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('index_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('index_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('index_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('index_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('index_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
                ('blog_list_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('blog_list_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('blog_list_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('blog_list_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('blog_list_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('blog_list_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
                ('grand_smeta_list_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('grand_smeta_list_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('grand_smeta_list_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('grand_smeta_list_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('grand_smeta_list_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('grand_smeta_list_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
                ('one_c_list_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('one_c_list_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('one_c_list_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('one_c_list_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('one_c_list_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('one_c_list_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
                ('online_cashbox_list_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('online_cashbox_list_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('online_cashbox_list_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('online_cashbox_list_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('online_cashbox_list_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('online_cashbox_list_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
                ('schedule_table_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('schedule_table_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('schedule_table_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('schedule_table_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('schedule_table_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('schedule_table_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
                ('schedule_list_page_title', models.TextField(blank=True, null=True, verbose_name='Тег title')),
                ('schedule_list_page_meta_keywords', models.TextField(blank=True, null=True, verbose_name='Тег meta keywords')),
                ('schedule_list_page_meta_description', models.TextField(blank=True, null=True, verbose_name='Тег meta description')),
                ('schedule_list_page_meta_og_title', models.TextField(blank=True, null=True, verbose_name='Тег meta og:title')),
                ('schedule_list_page_meta_og_description', models.TextField(blank=True, null=True, verbose_name='Тег meta og:description')),
                ('schedule_list_page_meta_og_image', models.TextField(blank=True, null=True, verbose_name='Тег meta og:image')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
