# Generated by Django 2.2 on 2019-12-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_grandsmeta_art_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='one_c_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в Гранд Смета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='online_cash_box_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в Гранд Смета'),
        ),
    ]
