# Generated by Django 2.2 on 2020-01-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20191216_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='one_c_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в 1С'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='online_cash_box_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в Онлайн-кассах'),
        ),
    ]
