# Generated by Django 2.2 on 2020-08-12 17:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200812_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='index_page_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на главной странице'),
        ),
    ]
