# Generated by Django 2.2 on 2020-08-12 17:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200812_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='why_choose_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на главной странице'),
        ),
    ]
