# Generated by Django 2.2 on 2020-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200812_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='index_page_h1_text',
            field=models.TextField(blank=True, null=True, verbose_name='h1 тег на странице  главной странице'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='one_c_h1_text',
            field=models.TextField(blank=True, null=True, verbose_name='h1 тег на странице  "1C"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='online_cash_box_h1_text',
            field=models.TextField(blank=True, null=True, verbose_name='h1 тег на странице "Онлайн Кассы"'),
        ),
    ]
