# Generated by Django 2.2 on 2020-11-29 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_atr_alt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_auto_20200812_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoFormBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.BooleanField(default=True, verbose_name='Отображать "Политика конфеденциальности"?')),
                ('captcha', models.BooleanField(default=True, verbose_name='Использовать Google-Captcha?')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма отображаемая в новостях',
            },
        ),
        migrations.CreateModel(
            name='PromoVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP пользователя')),
                ('form_data', models.TextField(default='{}', verbose_name='Данные формы')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Пост')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заполненные данные с новостей',
                'verbose_name_plural': 'Заполненные данные с новостей',
            },
        ),
        migrations.CreateModel(
            name='PromoFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('email', 'Email'), ('tel', 'Телефон'), ('textarea', 'Большое поле для текста')], max_length=255, verbose_name='Тип поля')),
                ('field_placeholder', models.CharField(max_length=100, verbose_name='Название поля (макс. 100 символов)')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PromoFormBuilder', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля для формы',
            },
        ),
    ]
