# Generated by Django 2.2 on 2023-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20230113_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='educators_h1_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='<h1> тег на странице  "Преподаватели"'),
        ),
    ]
