# Generated by Django 2.2 on 2025-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20250314_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.TextField()),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отзыв ученика',
                'verbose_name_plural': 'Отзывы учеников',
            },
        ),
    ]
