# Generated by Django 2.2 on 2025-03-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_studentsreviews'),
        ('core', '0047_auto_20250116_0736'),
    ]

    operations = [
    ]
