# Generated by Django 2.2 on 2025-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_merge_20250325_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
