# Generated by Django 2.2 on 2020-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
