# Generated by Django 2.2 on 2020-02-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20191119_1339'),
        ('calls', '0002_auto_20200220_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
