# Generated by Django 2.2 on 2020-02-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='Номер телефона'),
        ),
    ]
