# Generated by Django 2.2 on 2020-02-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_auto_20200220_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки на звонки'},
        ),
    ]
