# Generated by Django 2.2 on 2020-02-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20200220_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
