# Generated by Django 2.2 on 2020-08-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20200220_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_agree',
            field=models.BooleanField(default=False, help_text='Отмечено если с политикой конфидецияальности ознакомлен', verbose_name='Ознокомолен'),
        ),
    ]
