# Generated by Django 2.2 on 2025-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_is_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
