# Generated by Django 2.2 on 2020-01-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обнавлено'),
        ),
    ]
