# Generated by Django 2.2 on 2020-02-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_auto_20200120_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
