# Generated by Django 2.2 on 2020-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_auto_20200220_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_agress',
            field=models.BooleanField(default=False, help_text='Отмечено если с политикой конфидецияальности ознакомлен', verbose_name='Ознокомолен'),
        ),
    ]
