# Generated by Django 2.2 on 2020-02-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0004_checkout_is_agress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='is_agress',
            new_name='is_agree',
        ),
    ]
