# Generated by Django 2.2 on 2020-08-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_merge_20191202_1206'),
        ('checkouts', '0005_auto_20200220_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='online_cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout', to='production.OnlineCashbox', verbose_name='Онлайн кассы'),
        ),
    ]
