# Generated by Django 2.2 on 2019-04-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Название 1С услуги')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('thumbnail', models.FileField(help_text='Предпочитаемые размеры 540x540', upload_to='production/one-c/', verbose_name='Изображение')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '1С',
                'verbose_name_plural': '1С',
            },
        ),
    ]
