# Generated by Django 2.2 on 2019-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('price_box', models.TextField(default='[]', verbose_name='Расценка')),
                ('thumbnail', models.FileField(help_text='Предпочитаемые размеры 540x540', upload_to='production/online-cashbox/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Онлайн касса',
                'verbose_name_plural': 'Онлайн кассы',
            },
        ),
    ]
