# Generated by Django 2.2 on 2019-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_onlinecashbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.TextField(help_text='Ссылка которая ведет для того, что бы поделиться ссылкой. Параметр <b>{url}</b> нужен для ссылки на стриницу, <b>{title}</b> - для названия, <b>{description}</b> - Описание и <b>{image}</b> для изображения', max_length=1000, verbose_name='Ссылка')),
                ('icon', models.CharField(help_text='Сюда вписывается название класса иконки из Font Awesome. Предосмотр: <i class="fa" id="id_icon_preview"></i>', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Поделиться',
                'verbose_name_plural': 'Ссылки поделится',
            },
        ),
        migrations.AddField(
            model_name='onlinecashbox',
            name='share_links',
            field=models.ManyToManyField(blank=True, to='production.ShareLinks', verbose_name='Share ссылки'),
        ),
    ]
