# Generated by Django 2.2 on 2019-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20190508_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('price_box', models.TextField(default='[]', verbose_name='Цены')),
            ],
            options={
                'verbose_name': 'Эл. подпись',
                'verbose_name_plural': 'Электронные подписи',
            },
        ),
    ]
