# Generated by Django 2.2 on 2019-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_electronicsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsignature',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='production/electronic-signature/', verbose_name='Изображение'),
        ),
    ]
