# Generated by Django 2.2 on 2019-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_electronicsignature_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsignature',
            name='share_links',
            field=models.ManyToManyField(blank=True, to='production.ShareLinks', verbose_name='Share ссылки'),
        ),
    ]
