# Generated by Django 2.2 on 2019-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_electronicsignature_share_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelinks',
            name='icon',
            field=models.CharField(help_text='Сюда вписывается название класса иконки из Font Awesome. Предосмотр: <i class="fa id_icon_preview"></i>', max_length=50, verbose_name='Иконка'),
        ),
    ]
