# Generated by Django 2.2 on 2019-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20190529_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelinks',
            name='icon',
            field=models.CharField(help_text='Сюда вписывается название класса иконки из <a href="https://fontawesome.com/v4.7.0/icons/" target="_blank">Font Awesome</a>. Предосмотр: <i class="fa id_icon_preview"></i>', max_length=50, verbose_name='Иконка'),
        ),
    ]
