# Generated by Django 2.2 on 2019-05-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20190529_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCashBoxPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('thumbnail', models.FileField(upload_to='online-cash-box/thumbnails/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайдер на странице Онлайн кассы',
                'verbose_name_plural': 'Слайдер на странице Онлайн кассы',
            },
        ),
    ]
