# Generated by Django 2.2 on 2019-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_onlinecashboxpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='onec',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='production/one-c/cover-images/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='onlinecashbox',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='production/online-cashbox/cover-images/', verbose_name='Обложка'),
        ),
    ]
