# Generated by Django 2.2 on 2019-06-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20190614_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='onec',
            name='price_box',
            field=models.TextField(default='[]', verbose_name='Расценка'),
        ),
    ]
