# Generated by Django 2.2 on 2019-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_onec_price_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='onec',
            name='share_links',
            field=models.ManyToManyField(blank=True, to='production.ShareLinks', verbose_name='Ссылки поделиться'),
        ),
    ]
