# Generated by Django 2.2 on 2019-09-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_onlinecashboximage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='one-c/single/sliders', verbose_name='Изображение')),
                ('one_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.OneC', verbose_name='1С')),
            ],
            options={
                'verbose_name': 'Изображения 1C',
                'verbose_name_plural': 'Изображения 1C',
            },
        ),
    ]
