# Generated by Django 2.2 on 2019-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_onlinecashboximage_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecimage',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Атрибут alt'),
        ),
    ]
