# Generated by Django 2.2 on 2019-12-02 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_onlinecashboximage_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='onec',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True, verbose_name='SLUG'),
        ),
        migrations.AddField(
            model_name='onlinecashbox',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True, verbose_name='SLUG'),
        ),
    ]
