# Generated by Django 2.2 on 2019-12-02 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_auto_20191202_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onec',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='onlinecashbox',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='SLUG'),
        ),
    ]
