# Generated by Django 2.2 on 2019-12-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_auto_20191202_1156'),
        ('production', '0022_onlinecashbox_image_title_alt'),
    ]

    operations = [
    ]
