# Generated by Django 2.2 on 2020-08-12 17:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_merge_20191202_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onec',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание'),
        ),
    ]
