# Generated by Django 2.2 on 2020-08-12 17:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_auto_20200812_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onec',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Краткое описание'),
        ),
    ]
