# Generated by Django 2.2 on 2020-08-12 17:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_auto_20200812_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecashbox',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='onlinecashbox',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
