# Generated by Django 2.2 on 2020-08-12 17:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_auto_20200812_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsignature',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
