# Generated by Django 2.2 on 2019-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Тело статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
