# Generated by Django 2.2 on 2019-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
    ]
