# Generated by Django 2.2 on 2019-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Тег meta description'),
        ),
        migrations.AddField(
            model_name='post',
            name='page_meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Тег meta keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='page_meta_og_description',
            field=models.TextField(blank=True, null=True, verbose_name='Тег meta og:description'),
        ),
        migrations.AddField(
            model_name='post',
            name='page_meta_og_image',
            field=models.TextField(blank=True, null=True, verbose_name='Тег meta og:image'),
        ),
        migrations.AddField(
            model_name='post',
            name='page_meta_og_title',
            field=models.TextField(blank=True, null=True, verbose_name='Тег meta og:title'),
        ),
        migrations.AddField(
            model_name='post',
            name='page_title',
            field=models.TextField(blank=True, null=True, verbose_name='Тег title'),
        ),
    ]
