# Generated by Django 2.2 on 2019-11-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191116_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='atr_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Атрибут alt'),
        ),
    ]
