# Generated by Django 2.2 on 2020-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_atr_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Включить заполнение данных'),
        ),
    ]
