# Generated by Django 2.2 on 2019-05-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('thumbnail', models.FileField(help_text='Предпочитаемые размеры: 540x380', upload_to='schedule-objects/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(help_text='URL endpoint name', max_length=255, unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Учебный центр',
            },
        ),
        migrations.CreateModel(
            name='CourseActionDateObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Уберите этот флажок и эта дата станет не активная. Сайт будет брать дату начала обучения и кол-во свободных мест из <b>первого актуального</b> объекта даты среди всех <b>активных</b>', verbose_name='Активна?')),
                ('is_actual', models.BooleanField(default=True, help_text='Уберите этот флажок и записи на эту дату прекратятся', verbose_name='Актуально?')),
                ('action_date', models.DateTimeField(verbose_name='Дата начала курса')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
                ('cost', models.CharField(max_length=255, verbose_name='Стоимость курса')),
                ('max_people_in_course', models.PositiveIntegerField(default=0, verbose_name='Максимальное количество мест на обучение')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация о курсе',
            },
        ),
    ]
