# Generated by Django 2.2 on 2019-05-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190527_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseactiondateobject',
            name='cost',
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.CharField(max_length=255, null=True, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(help_text='Это расписание будет отображаться на странице расписани', max_length=255, null=True, verbose_name='Расписание занятий'),
        ),
    ]
