# Generated by Django 2.2 on 2019-05-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190527_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('is_reacted', models.BooleanField(default=False, verbose_name='Отреагировано?')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('education', models.CharField(max_length=255, verbose_name='Оброзование')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.CourseActionDateObject', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы на запись',
            },
        ),
    ]
