# Generated by Django 2.2 on 2019-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_applyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrequest',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
