# Generated by Django 2.2 on 2019-05-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_applyrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержденно?'),
        ),
    ]
