# Generated by Django 2.2 on 2019-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190528_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='schedule-objects/cover-images/', verbose_name='Обложка'),
        ),
    ]
