# Generated by Django 2.2 on 2019-06-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190614_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования(Словарь)',
            },
        ),
        migrations.AlterField(
            model_name='applyrequest',
            name='education',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Educations', verbose_name='Оброзование'),
        ),
    ]
