# Generated by Django 2.2 on 2019-06-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190614_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyrequest',
            name='name',
        ),
    ]
