# Generated by Django 2.2 on 2019-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_onec_share_links'),
        ('schedule', '0011_remove_applyrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='share_links',
            field=models.ManyToManyField(blank=True, to='production.ShareLinks', verbose_name='Ссылки поделиться'),
        ),
    ]
