# Generated by Django 2.2 on 2019-11-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20191116_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='course',
            name='atr_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Атрибут alt'),
        ),
    ]
