# Generated by Django 2.2 on 2020-12-11 06:26

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20191119_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(upload_to=core.utils.SetUniqueName(), verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ('order_index',),
            },
        ),
    ]
