# Generated by Django 2.2 on 2023-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_educators_photo_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educators',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение атрибута alt'),
        ),
    ]
