# Generated by Django 2.2 on 2023-01-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_educators_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='educators',
            name='page_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='META Description'),
        ),
        migrations.AddField(
            model_name='educators',
            name='page_meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='META Keywords'),
        ),
        migrations.AddField(
            model_name='educators',
            name='page_meta_og_description',
            field=models.TextField(blank=True, null=True, verbose_name='META og:description'),
        ),
        migrations.AddField(
            model_name='educators',
            name='page_meta_og_image',
            field=models.TextField(blank=True, null=True, verbose_name='META og:image'),
        ),
        migrations.AddField(
            model_name='educators',
            name='page_meta_og_title',
            field=models.TextField(blank=True, null=True, verbose_name='META og:title'),
        ),
        migrations.AddField(
            model_name='educators',
            name='page_title',
            field=models.TextField(blank=True, null=True, verbose_name='Значение <title>'),
        ),
    ]
