# Generated by Django 2.2 on 2025-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_studentsreviews'),
        ('schedule', '0025_auto_20230113_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_reviews',
            field=models.ManyToManyField(blank=True, to='core.StudentsReviews'),
        ),
    ]
