# Generated by Django 2.2 on 2025-03-14 14:43

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_course_student_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=255, verbose_name='Название CSS класса для иконки')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Приемущества курса',
                'verbose_name_plural': 'Приемущества курса',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255, verbose_name='CSS класс для иконки')),
                ('action_name', models.CharField(max_length=255, verbose_name='Текст на кнопке')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='banner_background',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.SetUniqueName('courses/banners')),
        ),
        migrations.AddField(
            model_name='course',
            name='course_roadmap_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_roadmap_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание под "Программа кураса"'),
        ),
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.SetUniqueName('courses/logos')),
        ),
        migrations.AddField(
            model_name='course',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='schedule.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic', to='schedule.SubscriptionPlans')),
            ],
            options={
                'verbose_name': 'Характеристика тарифа',
                'verbose_name_plural': 'Характеристики тарифов',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='advantages',
            field=models.ManyToManyField(blank=True, to='schedule.CourseAdvantages'),
        ),
        migrations.AddField(
            model_name='course',
            name='available_subscription_plans',
            field=models.ManyToManyField(blank=True, to='schedule.SubscriptionPlanCharacteristics'),
        ),
    ]
