# Generated by Django 2.2 on 2025-03-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20250314_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_subscription_plans',
            field=models.ManyToManyField(blank=True, to='schedule.SubscriptionPlans'),
        ),
    ]
