# Generated by Django 2.2 on 2025-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_auto_20250314_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
