# Generated by Django 2.2 on 2025-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_course_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplancharacteristics',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
