# Generated by Django 2.2 on 2025-03-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_subscriptionplans_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='available_subscription_plans',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_reviews',
        ),
    ]
