# Generated by Django 2.2 on 2025-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_auto_20250325_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, to='schedule.SubscriptionPlans'),
        ),
    ]
