# Generated by Django 2.2 on 2025-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_course_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_banner',
            field=models.BooleanField(default=True),
        ),
    ]
