# Generated by Django 2.2 on 2025-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_course_show_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='sort_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер для сортировки.'),
        ),
    ]
