# Generated by Django 2.2 on 2025-04-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0036_subscriptionplans_sort_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanCharacteristicsDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Словарь характеристик тарифов',
                'verbose_name_plural': 'Словарь характеристик тарифов',
            },
        ),
        migrations.AlterModelOptions(
            name='subscriptionplans',
            options={'ordering': ('sort_index',), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplancharacteristics',
            name='text',
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='icon',
            field=models.CharField(help_text='Сюда вписывается название класса иконки из <a href="https://fontawesome.com/v4.7.0/icons/" target="_blank">Font Awesome</a>. Предосмотр: <i class="fa id_icon_preview" data-syntax="full"></i>', max_length=255, verbose_name='CSS класс для иконки'),
        ),
        migrations.AddField(
            model_name='subscriptionplancharacteristics',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.SubscriptionPlanCharacteristicsDict'),
        ),
    ]
