# Generated by Django 2.2 on 2025-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0037_auto_20250421_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='payment_url',
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='action',
            field=models.CharField(choices=[('redirect', 'Перенаправить на другую страницу'), ('feedback', 'Показать форму обратной связи')], default='anchor', max_length=255, verbose_name='Действие на клик'),
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
